### ISSUE TITLE
Delete all versions from a schema

### ISSUE THREAD

**Issue by fraballi** [salsify/avro-schema-registry#183]
Great tool.
I need to create from scrash schemas in unit tests and deleting schemas is a must.
Does your API fully conforms with Confluent's? How can I delete a schema and all its versions?
e.g 

#### Delete version 3 of the schema registered under subject "Kafka-value"
```
$ curl -X DELETE http://localhost:8081/subjects/Kafka-value/versions/3
  3
```
#### Delete all versions of the schema registered under subject "Kafka-value"
```
$ curl -X DELETE http://localhost:8081/subjects/Kafka-value
  [1, 2, 3, 4, 5]
```

**Comment by jturkel** [comment]
We strive to keep the API compatible with the Confluent API but we haven't had a chance to implement the delete API yet. See #48 for the tracking issue for deletes. PRs are always welcome ;)
