### ISSUE TITLE
Upgrade to Rails 5.1

### ISSUE THREAD

**Issue by tjwp** [salsify/avro-schema-registry#53]
I created a branch for this: https://github.com/salsify/avro-schema-registry/tree/rails-5.1

I wasn't going to create a PR for this yet because I'm not actively using the schema registry yet.

**Comment by jturkel** [comment]
I'd love to see this land sooner rather than later. If you want to put up a PR, we would definitely get this live for Salsify.

**Comment by jturkel** [comment]
This was done in 9ab0f55118fab98eec743d06dfb1498dcbe1d4d4
